CREATE DATABASE IF NOT EXISTS loja;

USE loja;

CREATE TABLE
    IF NOT EXISTS CLIENTES(
        ID INT AUTO_INCREMENT,
        RG CHAR(9) NOT NULL,
        CPF CHAR(14) NOT NULL,
        ENDERECO VARCHAR(200) NOT NULL,
        BAIRRO VARCHAR(100) NOT NULL,
        CIDADE VARCHAR(100) NOT NULL,
        CEP CHAR(9) NOT NULL,
        EMAIL VARCHAR(200) NOT NULL,
        TELEFONE CHAR(15) NOT NULL,
        PRIMARY KEY(ID)
    );

CREATE TABLE
    IF NOT EXISTS PRODUTOS(
        ID INT AUTO_INCREMENT,
        NOME VARCHAR(200) NOT NULL,
        PRECO DECIMAL NOT NULL,
        QUANTIDADE INT NOT NULL,
        SEGMENTO VARCHAR(200) NOT NULL,
        PRIMARY KEY(ID)
    );

CREATE TABLE
    IF NOT EXISTS FUNCIONARIOS(
        ID INT AUTO_INCREMENT,
        RG CHAR(9) NOT NULL,
        CPF CHAR(14) NOT NULL,
        ENDERECO VARCHAR(200) NOT NULL,
        BAIRRO VARCHAR(100) NOT NULL,
        CIDADE VARCHAR(100) NOT NULL,
        CEP CHAR(9) NOT NULL,
        EMAIL VARCHAR(200) NOT NULL,
        TELEFONE CHAR(15) NOT NULL,
        FUNCAO VARCHAR(200) NOT NULL,
        DEPARTAMENTO VARCHAR(200) NOT NULL,
        PRIMARY KEY(ID)
    );

CREATE TABLE
    IF NOT EXISTS PAGAMENTO(
        ID INT AUTO_INCREMENT,
        FORMA ENUM(
            'CREDITO',
            'DEBITO',
            'PIX',
            'DINHEIRO'
        ),
        ID_PRODUTO INT NOT NULL,
        ID_CLIENTE INT NOT NULL,
        ID_FUNCIONARIO INT NOT NULL,
        PRIMARY KEY(ID),
        FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID),
        FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID),
        FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID)
    );