/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geinformatica;

import geinformatica.screens.LoginScreen;

public class App {

    public static void main(String[] args) {
        new LoginScreen();
    }
}
