-- Active: 1660569814330@@127.0.0.1@3306@ge_informatica

CREATE DATABASE IF NOT EXISTS ge_informatica;

USE ge_informatica;

CREATE TABLE
    IF NOT EXISTS USUARIOS(
        `ID` INT AUTO_INCREMENT,
        `NOME` VARCHAR(100) NOT NULL,
        `LOGIN` VARCHAR(100) UNIQUE NOT NULL,
        `SENHA` VARCHAR(50) NOT NULL,
        `TELEFONE` CHAR(15) NOT NULL,
        PRIMARY KEY(ID)
    );

CREATE TABLE
    IF NOT EXISTS CLIENTES(
        `ID` INT AUTO_INCREMENT,
        `NOME` VARCHAR(100) NOT NULL,
        `CPF` CHAR(11) NOT NULL,
        `ENDERECO` VARCHAR(100) NOT NULL,
        `CIDADE` VARCHAR(100) NOT NULL,
        `TELEFONE` CHAR(15) NOT NULL,
        `EMAIL` VARCHAR(200) NOT NULL,
        PRIMARY KEY(ID)
    );

CREATE TABLE
    IF NOT EXISTS ORDENS_DE_SERVICO(
        ID INT AUTO_INCREMENT,
        DATA_OS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        EQUIPAMENTO VARCHAR(255) NOT NULL,
        DEFEITO VARCHAR(255) NOT NULL,
        SERVICO VARCHAR(255) NOT NULL,
        TECNICO VARCHAR(100) NOT NULL,
        VALOR DECIMAL NOT NULL,
        ID_CLIENTE INT NOT NULL,
        PRIMARY KEY(ID),
        FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID)
    );