SELECT * FROM USUARIOS;

ALTER TABLE USUARIOS
ADD COLUMN PERFIL VARCHAR(50) NOT NULL;

UPDATE USUARIOS
SET PERFIL = "user"
WHERE ID <> 1;

INSERT INTO USUARIOS(NOME, LOGIN, SENHA, TELEFONE, PERFIL) VALUE('Melinne', 'mel', '1234', '+55092966666666', 'user'); 

UPDATE USUARIOS
SET PERFIL = "admin"
WHERE ID = 1;
